### PR TITLE
Tweaks for Superpowers 2

### PR DESCRIPTION
**Pull request by icarito**

### CODE REVIEW

**Comment by antca** [comment]
Thanks for the PR :+1:. I will check this soon.

**Comment by icarito** [comment]
We're at SuperPowers 3 already! :-D

My patch makes the UI work and part of the functionality but I still can't make it work. Your guidance would be appreciated, thanks!

**Comment by antca** [comment]
Sorry for the delay. Yes some of the plugin APIs have changed since 1.0, I am working on a fix. I would prefer to merge this PR on the develop branch. It's possible for you to switch the branch directly on Github ?

**Comment by soundyogi** [comment]
+1 Having this working would make Superpowers SO much more useful

**Comment by antca** [comment]
I have manually cherry-picked these commits into an other pull request on the develop branch. The changes are in the release 0.3.0.

**Pull request closed without merging**
